---
- name: "checkout ardupilot {{item.key}} source"
  git:
    repo: "{{repo}}"
    dest: "{{base}}/build/ardupilot"
    update: yes
    recursive: yes
    version: "{{item.value}}"
- name: "set target board to navio2"
  shell: "{{WAF_BIN}} configure --board=navio2"
  vars:
    WAF_BIN: "{{base}}/build/ardupilot/modules/waf/waf-light"
  args:
    chdir: "{{base}}/build/ardupilot"
- name: "build {{item.key}}"
  shell: "{{WAF_BIN}} {{item.key}}"
  vars:
    WAF_BIN: "{{base}}/build/ardupilot/modules/waf/waf-light"
  args:
    chdir: "{{base}}/build/ardupilot"