name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: run playbook
      run: |
        ansible-playbook -i hosts.yml playbook.yml

    # Upload ardupilot binaries for navio2
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /opt/dist/navio2.tar.xz
